### ISSUE TITLE
Cant boot from m.2 unless I boot override

### ISSUE THREAD

**Issue by carlosxfigueroa** [Errrneist/Hackintosh-Razer-Blade-Advanced#2]
I cant boot off the m.2 setting it up as the boot device just sends me to bios unless I boot override

**Comment by wu-hongjun** [comment]
> I cant boot off the m.2 setting it up as the boot device just sends me to bios unless I boot override

Your EFI is broken.

**Comment by carlosxfigueroa** [comment]
uhm i was able to fix it, efi wasnt broken its actually a common issue, also why havent you set audio to layout id 3? i was able to remove the boot-arg because of this, also seems like the nvidia gpu isnt properly disabled

**Comment by wu-hongjun** [comment]
> uhm i was able to fix it, efi wasnt broken its actually a common issue, also why havent you set audio to layout id 3? i was able to remove the boot-arg because of this, also seems like the nvidia gpu isnt properly disabled

Everyone's machine is different and this version works flawlessly for me. Your mileage might vary... I am just posting it here so people have something to look at

**Comment by carlosxfigueroa** [comment]
i have the same model as you, and i get 2 hours battery life

**Comment by wu-hongjun** [comment]
> i have the same model as you, and i get 2 hours battery life

I actually never tested the battery life on this one, it's quarantine and it's been up and running plugged in for like half a year lol so it might be a problem I also have no idea how to fix it
