### ISSUE TITLE
Would your trackpad working?

### ISSUE THREAD

**Issue by loadnl** [Errrneist/Hackintosh-Razer-Blade-Advanced#3]
Firstly thank you for your work!

I used your efi on 11 beta 3, every thing work except trackpad.

**Comment by wu-hongjun** [comment]
Yes. My trackpad is working perfectly. The only thing that doesn't work is thunderbolt 3 eGPU which I've been struggling for two months still can't fix it.

**Comment by loadnl** [comment]
Thank you for your answer, I find solution in another github user.
