### ISSUE TITLE
dGPU Not Off

### ISSUE THREAD

**Issue by boyuanx** [Errrneist/Hackintosh-Razer-Blade-Advanced#5]
Hey there, 

I noticed your configs fail to power down the RTX card, significantly increasing power draw and heat. The fix can be found here: https://github.com/stonevil/Razer_Blade_Advanced_early_2019_Hackintosh/issues/19#issuecomment-632171858

**Comment by wu-hongjun** [comment]
Good catch! As I mentioned in the other issue, my macOS partition is gone now and I need to prepare for my upcoming GRE exam (ughhhhh) so I am unable to fix it, for now, however I added some words in the readMe.MD/dGPU on this issue! Thanks again.
